# Use root/example as user/password credentials
version: '3.1'

services:

  institute-person-db:
    image: institute-person-db
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  institute-person-api:
    image: institute-person-api
    restart: always
    ports:
      - 8081:8081
