name: Build and Push Docker Image
run-name: ${{ github.actor }} ran Build and Push

on:
  push:
    branches:
      - feature-test
   
env:
  AWS_REGION: us-east-1                              ## set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: mentorhub           # set this to your Amazon ECR repository name
                                          
jobs:
   check-links:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          AWS_DEFAULT_REGION:
          AWS_REGION:
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
          AWS_SESSION_TOKEN:
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      #    aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build and push
        id: build-image
        uses: docker/build-push-action@v5
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: mentorHub-person-api:DEV-${{ github.sha }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./src/docker/Dockerfile 
          push: true
          tags: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  
