name: Build and Push Docker Image
run-name: ${{ github.actor }} ran Build and Push

on:
  push:
    branches:
      - feature-test
   
env:
  AWS_REGION: us-east-1                              ## set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: mentorhub           ## set this to your Amazon ECR repository name
                                          
jobs:
   check-links:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
          AWS_SESSION_TOKEN:
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k4m2e4q5/mentorhub


      - name: Build and push Multi-Platform Image
        id: build-image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          ECR_IMAGE="105886329607.dkr.ecr.us-east-1.amazonaws.com/your-repo-name"
          docker buildx build --platform linux/amd64,linux/arm64 -t $ECR_IMAGE:latest -t $ECR_IMAGE:${{ github.sha }} . -f /home/runner/work/mentorHub-person-api/mentorHub-person-api/src/docker/Dockerfile
          PUBLIC_ECR_IMAGE="public.ecr.aws/$ECR_IMAGE"
          docker tag $ECR_IMAGE:latest $PUBLIC_ECR_IMAGE:latest
          docker tag $ECR_IMAGE:${{ github.sha }} $PUBLIC_ECR_IMAGE:${{ github.sha }}

          docker push $ECR_IMAGE:latest
          docker push $ECR_IMAGE:${{ github.sha }}
          docker push $PUBLIC_ECR_IMAGE:latest
          docker push $PUBLIC_ECR_IMAGE:${{ github.sha }}
  
        
